#!/bin/bash

echo
echo	
echo Func tests:
echo
echo
for ((i = 0; i < 3; i++))
do
	for ((j = 1; j < 4; j++))
	do
		./main.out tests/func/in"$i"_1.txt tests/func/in"$i"_2.txt $j tests/out.txt
		if cmp -s tests/out.txt tests/func/out"$i"_"$j".txt; then
			echo Test $i with option - $j is GOOD
		else
			echo Test $i with optioin - $j is BAD
		fi
		echo
	done
done
